*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZRPD_EGDGR_V_SRU................................*
FORM GET_DATA_ZRPD_EGDGR_V_SRU.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZRPD_EGDGR_SRU WHERE
(VIM_WHERETAB) .
    CLEAR ZRPD_EGDGR_V_SRU .
ZRPD_EGDGR_V_SRU-MANDT =
ZRPD_EGDGR_SRU-MANDT .
ZRPD_EGDGR_V_SRU-FORM_ID =
ZRPD_EGDGR_SRU-FORM_ID .
ZRPD_EGDGR_V_SRU-KAT_ID =
ZRPD_EGDGR_SRU-KAT_ID .
ZRPD_EGDGR_V_SRU-SORU_ID =
ZRPD_EGDGR_SRU-SORU_ID .
ZRPD_EGDGR_V_SRU-SORU =
ZRPD_EGDGR_SRU-SORU .
ZRPD_EGDGR_V_SRU-TIP =
ZRPD_EGDGR_SRU-TIP .
ZRPD_EGDGR_V_SRU-SIRA =
ZRPD_EGDGR_SRU-SIRA .
<VIM_TOTAL_STRUC> = ZRPD_EGDGR_V_SRU.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZRPD_EGDGR_V_SRU .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZRPD_EGDGR_V_SRU.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZRPD_EGDGR_V_SRU-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZRPD_EGDGR_SRU WHERE
  FORM_ID = ZRPD_EGDGR_V_SRU-FORM_ID AND
  KAT_ID = ZRPD_EGDGR_V_SRU-KAT_ID AND
  SORU_ID = ZRPD_EGDGR_V_SRU-SORU_ID .
    IF SY-SUBRC = 0.
    DELETE ZRPD_EGDGR_SRU .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZRPD_EGDGR_SRU WHERE
  FORM_ID = ZRPD_EGDGR_V_SRU-FORM_ID AND
  KAT_ID = ZRPD_EGDGR_V_SRU-KAT_ID AND
  SORU_ID = ZRPD_EGDGR_V_SRU-SORU_ID .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZRPD_EGDGR_SRU.
    ENDIF.
ZRPD_EGDGR_SRU-MANDT =
ZRPD_EGDGR_V_SRU-MANDT .
ZRPD_EGDGR_SRU-FORM_ID =
ZRPD_EGDGR_V_SRU-FORM_ID .
ZRPD_EGDGR_SRU-KAT_ID =
ZRPD_EGDGR_V_SRU-KAT_ID .
ZRPD_EGDGR_SRU-SORU_ID =
ZRPD_EGDGR_V_SRU-SORU_ID .
ZRPD_EGDGR_SRU-SORU =
ZRPD_EGDGR_V_SRU-SORU .
ZRPD_EGDGR_SRU-TIP =
ZRPD_EGDGR_V_SRU-TIP .
ZRPD_EGDGR_SRU-SIRA =
ZRPD_EGDGR_V_SRU-SIRA .
    IF SY-SUBRC = 0.
    UPDATE ZRPD_EGDGR_SRU .
    ELSE.
    INSERT ZRPD_EGDGR_SRU .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZRPD_EGDGR_V_SRU-UPD_FLAG,
STATUS_ZRPD_EGDGR_V_SRU-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZRPD_EGDGR_V_SRU.
  SELECT SINGLE * FROM ZRPD_EGDGR_SRU WHERE
FORM_ID = ZRPD_EGDGR_V_SRU-FORM_ID AND
KAT_ID = ZRPD_EGDGR_V_SRU-KAT_ID AND
SORU_ID = ZRPD_EGDGR_V_SRU-SORU_ID .
ZRPD_EGDGR_V_SRU-MANDT =
ZRPD_EGDGR_SRU-MANDT .
ZRPD_EGDGR_V_SRU-FORM_ID =
ZRPD_EGDGR_SRU-FORM_ID .
ZRPD_EGDGR_V_SRU-KAT_ID =
ZRPD_EGDGR_SRU-KAT_ID .
ZRPD_EGDGR_V_SRU-SORU_ID =
ZRPD_EGDGR_SRU-SORU_ID .
ZRPD_EGDGR_V_SRU-SORU =
ZRPD_EGDGR_SRU-SORU .
ZRPD_EGDGR_V_SRU-TIP =
ZRPD_EGDGR_SRU-TIP .
ZRPD_EGDGR_V_SRU-SIRA =
ZRPD_EGDGR_SRU-SIRA .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZRPD_EGDGR_V_SRU USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZRPD_EGDGR_V_SRU-FORM_ID TO
ZRPD_EGDGR_SRU-FORM_ID .
MOVE ZRPD_EGDGR_V_SRU-KAT_ID TO
ZRPD_EGDGR_SRU-KAT_ID .
MOVE ZRPD_EGDGR_V_SRU-SORU_ID TO
ZRPD_EGDGR_SRU-SORU_ID .
MOVE ZRPD_EGDGR_V_SRU-MANDT TO
ZRPD_EGDGR_SRU-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZRPD_EGDGR_SRU'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZRPD_EGDGR_SRU TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZRPD_EGDGR_SRU'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
